### ISSUE TITLE
Calendarhelper failing with debug="false"

### ISSUE THREAD

**Issue by Ladefuss** [greystate/Greystate-XSLT-Helpers#44]
Umbraco version: 7.2.4
Calendarhelper version - lastest from https://github.com/greystate/Greystate-XSLT-Helpers/tree/master/dist/xslt/helpers

Calendarhelper failing if debug="false" in web.config on <compilation defaultLanguage="c#" debug="false" batch="false" targetFramework="4.5"> node.

Works with a "true" setting which we obviously cannot use on live environment.

**Comment by greystate** [comment]
Thanks for reporting this — any ideas as to what could cause this?

**Comment by Ladefuss** [comment]
Just including the helper file will generate "Saving XSLT file failed:" error i Umbraco backoffice.

    "[Thread 19] Error loading XSLT Calendar.xslt. Exception: System.Xml.Xsl.XslLoadException: Expression must evaluate to a node-set.
    -->$events<-- An error occurred at D:\Mercurial\db-test-debug\xslt\_CalendarHelper.xslt(198,7).
    at System.Xml.Xsl.XslCompiledTransform.LoadInternal(Object stylesheet, XsltSettings settings, XmlResolver stylesheetResolver)
    at umbraco.macro.CreateXsltTransform(XmlTextReader xslReader, Boolean debugMode)
    at umbraco.macro.<>c__DisplayClass12.<getXslt>
      b__11()
      at Umbraco.Core.CacheHelper.<>c__DisplayClass6`1.<GetCacheItem>
        b__4()
        at System.Lazy`1.CreateValue()
        at System.Lazy`1.LazyInitValue()
        at System.Lazy`1.get_Value()
        at Umbraco.Core.Cache.HttpRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, CacheDependency dependency)
        at Umbraco.Core.CacheHelper.GetCacheItem[TT](String cacheKey, CacheItemPriority priority, CacheDependency cacheDependency, Func`1 getCacheItem)
        at umbraco.macro.getXslt(String XsltFile)
        at umbraco.macro.LoadMacroXslt(macro macro, MacroModel model, Hashtable pageElements, Boolean throwError)
        2015-12-10 11:33:17,063 [8] WARN  umbraco.macro - [Thread 46] Error loading XSLT Calendar.xslt. Exception: System.Xml.Xsl.XslLoadException: Expression must evaluate to a node-set.
        -->$events<-- An error occurred at D:\Mercurial\db-test-debug\xslt\_CalendarHelper.xslt(198,7).
        at System.Xml.Xsl.XslCompiledTransform.LoadInternal(Object stylesheet, XsltSettings settings, XmlResolver stylesheetResolver)
        at umbraco.macro.CreateXsltTransform(XmlTextReader xslReader, Boolean debugMode)
        at umbraco.macro.<>c__DisplayClass12.<getXslt>
          b__11()
          at Umbraco.Core.CacheHelper.<>c__DisplayClass6`1.<GetCacheItem>b__4()
       at System.Lazy`1.CreateValue()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Lazy`1.get_Value()
       at Umbraco.Core.Cache.HttpRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, CacheDependency dependency)
       at Umbraco.Core.CacheHelper.GetCacheItem[TT](String cacheKey, CacheItemPriority priority, CacheDependency cacheDependency, Func`1 getCacheItem)
       at umbraco.macro.getXslt(String XsltFile)
       at umbraco.macro.LoadMacroXslt(macro macro, MacroModel model, Hashtable pageElements, Boolean throwError)

    
The $events variable is the nodeset i enclose in the param "events" to the "BuildCalendar" named template in the helper. 

So far we are working on the leads from https://our.umbraco.org/projects/backoffice-extensions/angulargooglemaps/bugs/60224-Problems-with-missing-debug=true-in-webconfig.

Could be a problem with the he Exslt Redux package https://github.com/leekelleher/umbraco-7-exslt-redux maby?

Can you reproduce this at all?

**Comment by greystate** [comment]
The error looks weird to me (sounds more like wrong input) - you're certain that setting `debug=true` renders the calendar _as expected,_ whreas `debug=false` fails?

The line number (198) doesn't match up with the latest file in the repo - which line does that linenumber in your file correspond to in the repo-file?

Not able to try reproducing this at the moment, sorry.

**Comment by Ladefuss** [comment]
Lets close it. Clearly not your code that creates the problem.
I saved lots of hours using the helper.

Have a great day

**Comment by greystate** [comment]
No problem :+1:
